# Generated by Django 3.1 on 2020-10-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
